---
ID: "eb5ef213-5a69-4594-b2e7-29e55edb8481"
Parent: "119af666-73e5-4d85-a7e1-da443beb81a3"
Template: "dbf95b59-47d0-4b49-b686-1a6b72cd67a6"
Path: /sitecore/content/SXA Reference/Playground/int/Settings
DB: master
BranchID: "b90549b5-c997-4d6b-b102-c9ab82528974"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {11F57D7B-CBB2-4647-B98C-71457564BA4F}
    {F86FE270-00A4-492F-BFAF-5BF27E40CE13}
    {70461699-48E4-45FA-B74B-0CCE849FCA6A}
    {20EF5E69-B366-4E9E-960B-E451B24DBD46}
    {5C76AD53-96CD-4B96-9690-DD9AF2650171}
    {44936C95-BCA9-4FB3-9D98-2066A5FBBB4D}
    {DC66D5DA-3216-48E6-AE78-BAC8445B6A46}
    {0D792404-79AA-483D-BB0C-50785F2E295B}
    {E1CF805E-7F49-4EC9-A25A-182DC798CB5F}
    {B14BAB5B-8965-466B-886B-1F93175BCAB3}
    {041C1F9F-99A4-4EE6-8308-985499F91032}
    {5A6BF1D1-836B-425A-A6E6-32CEAA8FF3A5}
- ID: "af332c24-fe17-41e7-8caf-8e64c588fe72"
  Hint: EditingTheme
  Value: "{0CA7940E-44D0-4387-AF1D-C989C22FD295}"
- ID: "beeede03-ab13-4558-96f9-c3e8957b46f8"
  Hint: Themes
  Type: Treelist
  Value: |
    {3F46272C-F3B8-4913-8C00-3816B436A4D3}
    {B38FC757-8CDF-4339-8907-BFFB445DBDE8}
- ID: "e81e1f9e-8b87-495b-9cb7-84a2a23133be"
  Hint: MediaLibrary
  Value: "{B79D48B4-B2EC-4E37-9EC3-A2FFED9A7C65}"
- ID: "e8881464-38af-4655-be4a-ee10586578a2"
  Hint: Templates
  Value: "{1530FE31-19BD-4059-8F9C-ADABCA39D828}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170212T133339Z
    - ID: "4b5d1cb7-e617-4cd0-a7e8-cc8a9fd80688"
      Hint: Rule
      Type: Rules
      Value: |
        <ruleset>
          <rule
            uid="{2444CF9C-DB60-4373-9825-F363D7A65FB5}">
            <conditions>
              <condition
                id="{E7888105-3B3F-4BD1-B60F-5461EEF4A811}"
                uid="9D331B65FCCD456ABC9FD79FA765471E"
                operatorid="{10537C58-1684-4CAB-B4C0-40C10907CE31}"
                value="{81003E8D-4232-433D-849E-6CA9574B5BD1}" />
            </conditions>
            <actions>
              <action
                id="{607FBC3F-6DD1-49C9-9930-0FBD06B99C31}"
                uid="BEA803F6456244ACB9B2B24E9B20A513"
                levels="2" />
            </actions>
          </rule>
        </ruleset>
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\Admin
