---
ID: "dbf95b59-47d0-4b49-b686-1a6b72cd67a6"
Parent: "1530fe31-19bd-4059-8f9c-adabca39d828"
Template: "ab86861a-6030-46c5-b394-e8f99e8b87db"
Path: /sitecore/templates/Project/SXA Reference/Playground/Settings
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/gearwheels.png
- ID: "12c33f3f-86c5-43a5-aeb4-5598cec45116"
  Hint: __Base template
  Type: tree list
  Value: |
    {8517DBE7-68BC-4700-AD41-379C4EBB76A0}
    {D81B405A-B997-4ACE-9068-A15E179A5419}
    {35EBD280-C9BE-4E49-BFAE-F90A32C019DD}
    {6175F4C7-F87F-4F7F-928E-4C5CA5DFFAF4}
    {C6E5A68F-8493-42F3-A8B4-C7FA8A5FB31D}
    {E34966E9-E83A-4C9C-A191-6B54B8DE0254}
    {03CA361C-8524-4505-8EED-2DF7E3C37159}
    {A7228B46-610D-4A17-9F61-649F3A30AAAE}
    {59F55DFC-4DB7-422F-9D40-F2ECF66C8499}
    {9D81C61A-0341-4312-816D-E5204385EA3C}
- ID: "f7d48a55-2158-4f02-9356-756654404f73"
  Hint: __Standard values
  Value: "{9DCDC937-BAFF-483D-AEB9-30AAFC6CA3CD}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170212T133318Z
